package com.app.pro.podcastprime.constant

object K {

    const val PLAYBACK_NOTIFICATION_CHANNEL_ID = "WDFWUJBQ0tfTk9USUZJQ0FUSU9OX0NIQU5ORUxfGED"

    const val PLAYBACK_NOTIFICATION_ID = 117584045

    const val MEDIA_ROOT_ID = "RSEESUFfUk9PVF9TYG"

    const val START_MEDIA_PLAYBACK_ACTION = "START_MEDIA_PLAYBACK_ACTION"

    const val REFRESH_MEDIA_BROWSER_CHILDREN = "REFRESH_MEDIA_BROWSER_CHILDREN"

    const val PLAYBACK_POSITION_UPDATE_INTERVAL = 1000L

    const val ACTION_PODCAST_NOTIFICATION_CLICK = "ACTION_PODCAST_NOTIFICATION_CLICK"
}